[package]
org = "ballerina"
name = "websub_advanced_integration_tests"
version = "1.0.8"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.5.4"

[[dependency]]
org = "ballerina"
name = "mime"
version = "1.0.4"

[[dependency]]
org = "ballerina"
name = "runtime"
version = "0.5.4"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.0.4"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.0.4"

[[dependency]]
org = "ballerina"
name = "auth"
version = "1.0.4"

[[platform.java11.dependency]]
path = "../websub-native/build/libs/websub-native-1.0.8-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "web-sub"
version = "1.0.8-SNAPSHOT"
