[[ballerina.auth.users]]
username="alice"
password="password1"
scopes=["scope1"]

[[ballerina.auth.users]]
username="bob"
password="password2"
scopes=["scope2", "scope3"]

[[ballerina.auth.users]]
username="eve"
password="password3"
